### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by emmaprofemx** [Blackhawk777/Thermal_Printer_Flutter#2]
I'm trying to play this project a device Android , but at the moment that I push button 'Search' not desplay nothing.

**Comment by Prithviraj2003** [comment]
same issue did you find the solution ?

**Comment by emmaprofemx** [comment]
@Prithviraj2003 Yeah , I used other project , but I needed to adapt it according to what I needed...

**Comment by Prithviraj2003** [comment]
can you please share the other project link you referred.

**Comment by emmaprofemx** [comment]
Check these two projects @Prithviraj2003 
https://github.com/andrey-ushakov/esc_pos_utils
https://github.com/marwenbk/flutter_pos_printer_platform

**Comment by Prithviraj2003** [comment]
Thank you for your support !!
